spring.application.name=JobApp
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/your-db-name
spring.datasource.username=your-db-username
spring.datasource.password=your-db-password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=your-openai-api-key
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.stream-usage=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB